# Generated by Django 4.0.3 on 2022-04-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='paciente',
        ),
    ]
