# Generated by Django 4.0.3 on 2022-04-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ots', '0002_remove_ordentrabajo_cargo_remove_ordentrabajo_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseresultados',
            name='ot',
        ),
    ]
