# Generated by Django 4.0.3 on 2022-04-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_ordentrabajo_cargo_remove_ordentrabajo_medico_and_more'),
        ('pacientes', '0001_initial'),
        ('ots', '0003_remove_baseresultados_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.cargo'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.medico'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
