# Generated by Django 4.0.3 on 2022-04-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_ordentrabajo_cargo_remove_ordentrabajo_medico_and_more'),
        ('pacientes', '0001_initial'),
        ('ots', '0005_baseresultados_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseresultados',
            name='ot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ots.ordentrabajo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cargo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.medico'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
