# Generated by Django 4.0.3 on 2022-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('udm', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=10)),
                ('siglas', models.CharField(max_length=15)),
            ],
        ),
    ]
