# Generated by Django 4.0.3 on 2022-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_corto', models.CharField(blank=True, max_length=80, null=True)),
                ('nota_Encabezado', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
