# Generated by Django 4.0.3 on 2022-04-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='nota_Pie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
