# Generated by Django 4.0.3 on 2022-04-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_analisis_nota_pie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.CharField(blank=True, max_length=10, null=True)),
                ('maximo', models.CharField(blank=True, max_length=10, null=True)),
                ('edad_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('edad_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sexo', models.CharField(max_length=2)),
                ('detalle', models.CharField(max_length=30)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.prueba')),
            ],
        ),
    ]
