# Generated by Django 4.0.3 on 2022-04-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_prueba_udm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicionAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.SmallIntegerField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.analisis')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.prueba')),
            ],
        ),
    ]
