# Generated by Django 4.0.3 on 2022-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_composicionanalisis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('notas', models.TextField()),
                ('default', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
