# Generated by Django 4.0.3 on 2022-04-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisValidosCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('nota', models.CharField(max_length=40)),
            ],
        ),
    ]
