# Generated by Django 4.0.3 on 2022-04-11 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_analisisvalidoscargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisvalidoscargo',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.cargo'),
        ),
        migrations.AlterField(
            model_name='analisisvalidoscargo',
            name='nota',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
