# Generated by Django 4.0.3 on 2022-04-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_analisisvalidoscargo_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisvalidoscargo',
            name='analisis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.analisis'),
        ),
    ]
