# Generated by Django 4.0.3 on 2022-04-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_analisisvalidoscargo_analisis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisvalidoscargo',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.analisis'),
        ),
        migrations.AlterField(
            model_name='analisisvalidoscargo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cargo'),
        ),
    ]
