# Generated by Django 4.0.3 on 2022-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_analisisvalidoscargo_analisis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=2)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
