# Generated by Django 4.0.3 on 2022-04-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_ordentrabajo_paciente_delete_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='BaseResultados',
        ),
        migrations.DeleteModel(
            name='OrdenTrabajo',
        ),
    ]
